version: "3.9"

services:
  postgres:
    image: postgres:14.3
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root"]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - APP_DB_USER=docker
      - APP_DB_PASS=docker
      - APP_DB_NAME=docker
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432

  # app:
  #   container_name: app
  #   restart: always
  #   build:
  #     context: .
  #   environment:
  #     DB_SCHEMA: ${DB_SCHEMA}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_HOST: ${DB_HOST}
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
# volumes:
#   zipcode-db:
